### ISSUE TITLE
Newer releases don't work on mac

### ISSUE THREAD

**Issue by liujoshua** [Terminal-Wallet/terminal-wallet-cli#8]
Version 1.0.2 works fine, versions 1.1.8 and 1.19 crash. I'm guessing this is mac specific?

```
$ ./terminal-wallet-macos
node:internal/fs/utils:347
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/private/var/folders/pp/sc06q5dd22l65q_k44r3216h0000gt/T/caxa/applications/terminal-wallet-cli/g9ua5rxeve/0/poseidon_hash_wasm_bg.wasm'
    at Object.openSync (node:fs:590:3)
    at Object.readFileSync (node:fs:458:35)
    at node_modules/@railgun-community/poseidon-hash-wasm/pkg-cjs/poseidon_hash_wasm.js (/private/var/folders/pp/sc06q5dd22l65q_k44r3216h0000gt/T/caxa/applications/terminal-wallet-cli/g9ua5rxeve/0/bundle.js:231470:32)
    at __require (/private/var/folders/pp/sc06q5dd22l65q_k44r3216h0000gt/T/caxa/applications/terminal-wallet-cli/g9ua5rxeve/0/bundle.js:12:51)
    at node_modules/@railgun-community/poseidon-hash-wasm/index.js (/private/var/folders/pp/sc06q5dd22l65q_k44r3216h0000gt/T/caxa/applications/terminal-wallet-cli/g9ua5rxeve/0/bundle.js:231481:16)
    at __require (/private/var/folders/pp/sc06q5dd22l65q_k44r3216h0000gt/T/caxa/applications/terminal-wallet-cli/g9ua5rxeve/0/bundle.js:12:51)
    at node_modules/@railgun-community/engine/dist/utils/poseidon.js (/private/var/folders/pp/sc06q5dd22l65q_k44r3216h0000gt/T/caxa/applications/terminal-wallet-cli/g9ua5rxeve/0/bundle.js:231521:38)
    at __require (/private/var/folders/pp/sc06q5dd22l65q_k44r3216h0000gt/T/caxa/applications/terminal-wallet-cli/g9ua5rxeve/0/bundle.js:12:51)
    at node_modules/@railgun-community/engine/dist/note/note-util.js (/private/var/folders/pp/sc06q5dd22l65q_k44r3216h0000gt/T/caxa/applications/terminal-wallet-cli/g9ua5rxeve/0/bundle.js:231688:22)
    at __require (/private/var/folders/pp/sc06q5dd22l65q_k44r3216h0000gt/T/caxa/applications/terminal-wallet-cli/g9ua5rxeve/0/bundle.js:12:51) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/private/var/folders/pp/sc06q5dd22l65q_k44r3216h0000gt/T/caxa/applications/terminal-wallet-cli/g9ua5rxeve/0/poseidon_hash_wasm_bg.wasm'
}

```

**Comment by linkismissing** [comment]
This issue should now be solved.
